title: Safe Workplace
description: A contact tracing app that helps business and offices to maintain social distancing by using check-in and check-out functionality.
show_downloads: true
theme: jekyll-theme-cayman
