# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [opened,reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      #- name: Notify Contact Tracing Teams Channel
      #  uses: aliencube/microsoft-teams-actions@v0.8.0
      #  with:
      #      webhook_uri: ${{ secrets.MS_TEAMS_CONTACTTRACING_WEBHOOK_URI }}
      #      title: '${{ github.event.issue.title }}'
      #      summary: 'Issue ${{ github.event.issue.number }}'
      #      text: 'New issue #${{ github.event.issue.number }} was created by ${{ github.event.issue.user.login }}'
      #      theme_color: dc3545
      #      # sections: '[{ "activityTitle": "hello world" }, { ... }]'
      #      actions: '[{ "@type": "OpenUri", "name": "View in GitHub", "targets": [{ "os": "default", "uri": "${{ github.event.issue.html_url }}" }] }]'

      - name: Add to Azure Boards
        uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.AZUREDEVOPS_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ github.token }}"
          ado_organization: "AKAES"
          ado_project: "SMB Covid-19 Contact Tracing App"
          ado_wit: "Bug"
          ado_new_state: "New"
          ado_bypassrules: true
